#ifndef NEWNEW_SCENESTATE_H
#define NEWNEW_SCENESTATE_H

enum SceneState {
    STATE_SCENE,
    STATE_TRANSITION_SCENE_IN,
    STATE_TRANSITION_SCENE_OUT,
    STATE_CHANGING_SCENE,
    STATE_SKIP_FRAME,
};

#endif //NEWNEW_SCENESTATE_H
