#ifndef NEWNEW_MENUSCREENPOSITION_H
#define NEWNEW_MENUSCREENPOSITION_H

enum ScreenPosition {
    TOP_LEFT, //1st quadrant, TODO: should I rename?
    TOP_SECOND_QUADRANT,
    TOP_THIRD_QUADRANT,
    TOP_RIGHT, //4th quadrant

    BOTTOM_LEFT, //1st quadrant
    BOTTOM_SECOND_QUADRANT,
    BOTTOM_THIRD_QUADRANT,
    BOTTOM_RIGHT, //4th quadrant

    CENTERED
};

#endif //NEWNEW_MENUSCREENPOSITION_H
