#ifndef NEWNEW_MENUSCREENPOSITION_H
#define NEWNEW_MENUSCREENPOSITION_H

enum ScreenPosition {
    TOP_LEFT,
    TOP_RIGHT,
    BOTTOM_LEFT,
    BOTTOM_RIGHT,
    CENTERED
};

#endif //NEWNEW_MENUSCREENPOSITION_H
