#ifndef NEWNEW_BATTLESTATE_H
#define NEWNEW_BATTLESTATE_H

enum BattleState {
    ENEMY_APPEARED_STATE,
    SHOW_BATTLE_CHOICES_STATE,
    RUN_AWAY_STATE,
    BATTLE_OVER
};

#endif //NEWNEW_BATTLESTATE_H
