#ifndef NEWNEW_UICOMPONENTTYPE_H
#define NEWNEW_UICOMPONENTTYPE_H

enum UIComponentType {
    NO_COMPONENT_TYPE,
    DIALOGUE_MENU,
    MENU_SELECTOR,
    START_MENU,
    PARTY_MENU,
    BATTLE_CHARACTER_CHOICES_MENU
};

#endif //NEWNEW_UICOMPONENTTYPE_H
