#ifndef NEWNEW_ENTITYSTATE_H
#define NEWNEW_ENTITYSTATE_H

enum EntityState {
    STATE_STANDING,
    STATE_MOVING,
    STATE_PLAYER_INTERACTING_WITH_UI,
    STATE_PLAYER_DONE_WITH_UI
};

#endif //NEWNEW_ENTITYSTATE_H
